// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxteqvfaoiobyfmluuje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4dGVxdmZhb2lvYnlmbWx1dWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMjM2ODUsImV4cCI6MjA2ODg5OTY4NX0.uCxHS9cU54QdY9eMeOvAF4V0MqlVP8xoYN4PBrAdT_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});